language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - pip install -e fortunate
    - pip install coveralls

script:
    - coverage run --source=fortunate fortunate/setup.py test

after_success:
    coveralls

notifcations:
    email: false
