language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "nightly"

before_install:
    - git clone https://github.com/kryptn/fortunate.git
    - cd fortunate

install:
    - pip install -e fortunate

script:
    - python -m fortunate.tests
